# Site settings
title: DoWhileGeek
copyright: Joeseph Rodrigues
header-img: img/home-bg.jpg
email: dowhilegeek@gmail.com
description: "Joeseph Rodrigues' personal tech blog."
baseurl: ""
url: "http://dowhilegeek.com"
twitter_username: dowhilegeek
github_username:  dowhilegeek

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
gems: ["jekyll-paginate"]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
